# Site settings
title: Angel Ortiz 
email: angelo12@vt.edu
description: > # this means to ignore newlines until "baseurl:"
  A website to showcase my work & personal projects
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: aortizelguero
github_username:  Angelo1211

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

plugins: [jekyll-paginate]
